### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by cliffordfajardo** [SeanJM/css-clean#1] opened 2016-01-18 07:10 UTC
**Steps to reproduce below:**

1. This was the SCSS file I tried to do "Css clean". https://gist.github.com/cliffordfajardo/b0b58cc76afcaef843cd
2. The error seems to be coming from line 79, when there is no closing semicolon. However, even with the semicolon added, the 'Cannot read property '0' of null' still occurs.
and the code around line 79 remains like so after running ' Css clean.
3. I removed the Sass inline comments form 82 - 86  of the gist and that completely solved the errors from steps 1 & 2.
```
.card-menu a {
 display        : inline-block;
 margin-right   : 20px;
 padding-top    : 15px;
 text-transform : uppercase;
 font-size      : 0.8em;
 font-weight : 500;
 color: black;
}
```

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3

TypeError: Cannot read property '0' of null
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2390)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at getGroup (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2811)
    at cleanCss (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:2941)
    at atom-text-editor.module.exports.convert (/Users/cliffordfajardo/.atom/packages/css-clean/lib/css-clean.js:3:9882)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:37.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23.5.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:23.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:20.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -0:17 core:save (atom-text-editor.editor.is-focused)
     -0:13.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.9.0 css-clean:convert (atom-text-editor.editor)
     -0:11.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 css-clean:convert (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "styleguide",
      "timecop",
      "package-generator",
      "about",
      "background-tips",
      "font-viewer",
      "pane-move-plus",
      "sync-settings",
      "atom-runner",
      "npm-plus",
      "autocomplete-modules",
      "atom-ternjs",
      "linter-jshint",
      "livestyle-atom",
      "linter-csslint",
      "linter-htmlhint"
    ],
    "packagesWithKeymapsDisabled": [
      "css-clean"
    ],
    "themes": [
      "atom-material-ui",
      "duotone-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
atom-beautify, v0.28.21
atom-fix-path, v0.1.0
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
autocomplete-project-paths, v2.2.0
autoprefixer, v3.1.0
browser-plus, v0.0.54
color-picker, v2.0.14
css-clean, v1.4.0
duotone-dark-syntax, v0.5.0
emmet, v2.3.17
file-icons, v1.6.13
git-time-machine, vundefined
linter, v1.11.3
linter-jsonlint, v1.1.4
package-settings, v1.0.1
pane-layout-plus, v0.7.3
pigments, v0.19.6
rest-client, v0.5.0
set-syntax, v0.3.0
svg-preview, v0.7.3
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by SeanJM** [comment] 2016-02-17 18:59
Fixed now

**Comment by HannesDev** [comment] 2016-03-29 21:29
Same Issue here.

`TypeError: Cannot read property '0' of null
    at Function.capture.comment inline (/Users/Hannes/.atom/packages/css-clean/main.js:194:14)
    at capture (/Users/Hannes/.atom/packages/css-clean/main.js:25:23)
    at Object.capture.property group.capture.sass each.capture.sass for.capture.sass import.capture.sass mixin.capture.shared.nested (/Users/Hannes/.atom/packages/css-clean/main.js:407:19)
    at Function.capture.selector (/Users/Hannes/.atom/packages/css-clean/main.js:155:26)
    at capture (/Users/Hannes/.atom/packages/css-clean/main.js:25:23)
    at capture.property group.capture.sass each.capture.sass for.capture.sass import.capture.sass mixin.cleanCss.fn.value (/Users/Hannes/.atom/packages/css-clean/main.js:508:19)
    at Object.value (/Users/Hannes/.atom/packages/css-clean/main.js:1338:24)
    at atom-text-editor.capture.property group.capture.sass each.capture.sass for.capture.sass import.capture.sass mixin.getValue.comment block.getValue.media query.getValue.sass import.lines.map.value.split.map.module.exports.convert (/Users/Hannes/.atom/packages/css-clean/main.js:1470:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)`

css-clean: 2.2.10
Atom: 1.6.0

**Comment by baki250** [comment] 2016-05-10 12:54
Same thing happens on comment:

`.toggleContent{
 // display: block;
 }`

Stack Trace:

`TypeError: Cannot read property '0' of null
    at Function.capture.comment inline (C:\Users\btoktas\.atom\packages\css-clean\main.js:194:14)
    at capture (C:\Users\btoktas\.atom\packages\css-clean\main.js:25:23)
    at Object.capture.shared.nested (C:\Users\btoktas\.atom\packages\css-clean\main.js:407:19)
    at Function.capture.selector (C:\Users\btoktas\.atom\packages\css-clean\main.js:155:26)
    at capture (C:\Users\btoktas\.atom\packages\css-clean\main.js:25:23)
    at Object.capture.shared.nested (C:\Users\btoktas\.atom\packages\css-clean\main.js:407:19)
    at Function.capture.selector (C:\Users\btoktas\.atom\packages\css-clean\main.js:155:26)
    at capture (C:\Users\btoktas\.atom\packages\css-clean\main.js:25:23)
    at Object.capture.shared.nested (C:\Users\btoktas\.atom\packages\css-clean\main.js:407:19)
    at Function.capture.selector (C:\Users\btoktas\.atom\packages\css-clean\main.js:155:26)
    at capture (C:\Users\btoktas\.atom\packages\css-clean\main.js:25:23)
    at Object.capture.shared.nested (C:\Users\btoktas\.atom\packages\css-clean\main.js:407:19)
    at Function.capture.selector (C:\Users\btoktas\.atom\packages\css-clean\main.js:155:26)
    at capture (C:\Users\btoktas\.atom\packages\css-clean\main.js:25:23)
    at Object.capture.shared.nested (C:\Users\btoktas\.atom\packages\css-clean\main.js:407:19)
    at Function.capture.selector (C:\Users\btoktas\.atom\packages\css-clean\main.js:155:26)
    at capture (C:\Users\btoktas\.atom\packages\css-clean\main.js:25:23)
    at cleanCss.fn.value (C:\Users\btoktas\.atom\packages\css-clean\main.js:508:19)
    at Object.value (C:\Users\btoktas\.atom\packages\css-clean\main.js:1419:24)
    at atom-text-editor.module.exports.convert (C:\Users\btoktas\.atom\packages\css-clean\main.js:1549:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\btoktas\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\btoktas\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\btoktas\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\btoktas\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\btoktas\AppData\Local\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)`

**Comment by jcsky** [comment] 2016-07-04 08:07
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.5.0


### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/sky/.atom/packages/css-clean/main.js:157

TypeError: Cannot read property '0' of null
    at Function.capture.comment inline (/Users/sky/.atom/packages/css-clean/main.js:157:14)
    at capture (/Users/sky/.atom/packages/css-clean/main.js:87:23)
    at Object.capture.shared.nested (/Users/sky/.atom/packages/css-clean/main.js:436:19)
    at Function.capture.selector (/Users/sky/.atom/packages/css-clean/main.js:107:26)
    at capture (/Users/sky/.atom/packages/css-clean/main.js:87:23)
    at cleanCss.fn.value (/Users/sky/.atom/packages/css-clean/main.js:592:19)
    at Object.value (/Users/sky/.atom/packages/css-clean/main.js:1617:24)
    at atom-text-editor.module.exports.convert (/Users/sky/.atom/packages/css-clean/main.js:1746:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -3:04.8.0 core:undo (atom-text-editor.editor.is-focused)
     -1:46.9.0 css-clean:convert (atom-text-editor.editor.is-focused)
     -1:44.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:41.8.0 core:redo (atom-text-editor.editor.is-focused)
     -1:31.7.0 core:undo (atom-text-editor.editor.is-focused)
     -1:21.7.0 core:redo (atom-text-editor.editor.is-focused)
  4x -1:11.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:04.1.0 core:redo (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:57.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:49.4.0 css-clean:convert (atom-text-editor.editor.is-focused)
     -0:40.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:36.5.0 core:redo (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:00.7.0 css-clean:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-bootlint",
      "webbox-color"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.2
autocomplete-elixir, v1.5.14
css-clean, v2.5.0
css-snippets, v0.9.0
emmet, v2.4.3
language-elixir, v0.14.0
language-haml, v0.24.0
linter, v1.11.14
linter-jshint, v2.1.0
linter-sass-lint, v1.6.1
merge-conflicts, v1.4.4
rails-i18n-autocomplete, v0.4.0

# Dev
No dev packages
```

**Comment by SeanJM** [comment] 2016-07-04 12:21
Fixed, just pushed a new version. Let me know if it fixes everything.

**Comment by HannesDev** [comment] 2016-08-06 09:17
Had the Issue in Atom 1.8.0
Updated to Atom 1.9.5 and it seems to be resolved. Thanks!

**Comment by SeanJM** [comment] 2016-08-07 12:04
Thank you.

**Closed by SeanJM** 2016-08-07 12:04 UTC
